# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8207687f9ad2584797f7e2fee5450a0ab8d2b02dc249026467b25ac5654011ff8950a1d851edf9bae884283b51dbbe518395e9e08976bc18df41fe01a9653086

test:
  secret_key_base: dc118d85949df75c89e2658123e34384831e9849ec0cd53ea8c6975d94b4edc680762fb534700310b0f56c05d5d548d3b14eb11c08f8d3297592d3e928d94a37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
