theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
toolbar1: alignleft aligncenter alignright alignjustify | bold italic | image media | undo redo | emoticons | forecolor backcolor
toolbar2:
plugins:
  - table
  - fullscreen
  - image
  - imagetools
  - media
  - emoticons
  - textcolor