theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
toolbar:
  - styleselect | bold | italic | undo redo | image | media | link
plugins:
  - textcolor
  - image
  - imagetools
  - colorpicker
  - media
  - link